name: ResidencePE
version: 0.0.1
api: 1.12.0
main: ResidencePE\ResidencePE
author: CreeperFace
description: Residence plugin ported from PC

commands:
    res:
        description: "main command for players"
        permission: res
    resadmiin:
        description: "main command for Admins"
        permission: resadmin

permissions:
    residence:
        description: "main permission"
        default: op
        children:
            residence.select:
                description: "select a cuboid area to protect, using either the selection tool (wooden axe by default) or specifying X, Y, and Z"
                default: op
            residence.select.vert:
                description: "expand selection from sky to bedrock"
                default: op
            residence.size:
                description: "show selected area size"
                default: op
            residence.create:
                description: "create a residence"
                default: op
            residence.remove:
                description: "remove a residence"
                default: op
            residence.current:
                description: "show residence you're currently in"
                default: op
            residence.info:
                description: "show info about specified residence"
                dafault: op
            residence.list:
                description: "list residences you own"
                default: op
            residence.listall:
                description: "list of all residences"
                default: op
            residence.pset:
                description: "set flags on different players"
                default: op
            residence.set:
                description: "set flags on residences"
                default: op
            residence.default:
                description: "Restores residence to default flags"
                default: op
            residence.give:
                description: "Gives residence to another player. Player must be online and you have to own the residence"
                default: op
            residence.message:
                description: "sets a enter or leave area message. You can ommit <residence> to use the one your standing in"
                default: op
            residence.message.remove:
                description: "removes a enter or leave message"
                default: op
            residence.rename:
                description: "Rename a residence. For subzones, OldName must the the full name(parent.subzone), while NewName is only the new name"
                default: op
            residence.tp:
                description: "teleport to a residence"
                default: op
            residence.tpset:
                description: "set the teleport location in your residence"
                default: op
            residence.unstuck:
                description: "moves you outside the protected area your in"
                default: op
            residence.market:
                description: "permission for economy actions"
                default: op
                children:
                    residence.market.list:
                        description: "view the list of residences for sale"
                        default: op
                    residence.market.info:
                        description: "view info on a residence for sale"
                        default: op
                    residence.market.sell:
                        description: "put up a residence for sale"
                        default: op
                    residence.market.unsell:
                        description: "stop selling a residence"
                        default: op
                    residence.market.buy:
                        description: "buy a residence"
                        default: op
    residenceadmin:
        description: "unlimited permissions for all residences"
        default: op