#These are Global Settings for Residence.
Global:
    # This loads the <language>.yml file in the Residence Language folder
    # All Residence text comes from this file. (NOT DONE YET)
    Language: English
    # Wooden Hoe is the default selection tool for Residence.
    # You can change it to another item ID listed here: http://www.minecraftwiki.net/wiki/Data_values
    SelectionToolId: 290
    # This determins which tool you can use to see info on residences, default is String.
    # Simply equip this tool and hit a location inside the residence and it will display the info for it.
    InfoToolId: 287
    # The interval, in minutes, between residence saves.
    SaveInterval: 10
    # The default group to use if Permissions fails to attach or your not using Permissions.
    DefaultGroup: default
    # Whether or not to use the Permissions system in conjunction with this config.
    EnablePermissions: true
    # Set to true if NOT using Permissions or PermissionsBukkit, or using a really old version of Permissions
    LegacyPermissions: false
    # Enable / Disable Residence's Economy System (PocketMoney, MassiveEconomy, €?onom?$).
    EnableEconomy: true
    # Enable or disable residence chat channels.
    ResidenceChatEnable: true
    # Color of residence chat.
    ResidenceChatColor: DARK_PURPLE
    # Whether or not to ignore the usual Permission flags and only allow OPs and groups with 'residence.admin' to change residences.
    AdminOnlyCommands: false
    # Setting this to true makes server OPs admins.
    AdminOPs: true
    # Setting this to false will cause residence to continue to load even if a error is detected in the save file.
    StopOnSaveFault: true
    # These are world flags that are applied when the player is NOT within a residence.
    Flags:
        Global: #these are default for all worlds unless specified below, they can be overridden per group
            use: true
            build: true
            ignite: true
            firespread: true
            damage: true
            creeper: true
            tnt: true
            pvp: true
        WorldNameHere: #here you can set flags for individual worlds, these override Global
            #build: true
    # This gives permission to change certain flags to all groups, unless specifically denied to the group.
    FlagPermission:
        move: true
        build: true
        place: true
        destroy: true
        use: true
        container: true
        pvp: true
        tp: true
        ignite: true
        firespread: true
        bucket: true
        flow: true
        lavaflow: true
        waterflow: true
        creeper: true
        tnt: true
        monsters: true
        animals: true
        subzone: true
        healing: true
        piston: true
        diode: true
        lever: true
        button: true
        door: true
        table: true
        enchant: true
        brew: true
        bed: true
        cake: true
        note: true
        trample: false
        burn: true
        explode: false
        fireball: true
    # These are default flags applied to all residences from any user group.
    ResidenceDefault:
        build: false
        use: false
        container: false
        pvp: false
        tnt: false
        creeper: false
        flow: false
        piston: false
        ignite: false
        firespread: false
    # These are default flags applied to the residence creator of any group.
    CreatorDefault:
        build: true
        move: true
        use: true
        ignite: true
        container: true
     # These are default group flags applied to a residence made by a user of any group.
    GroupDefault:
        #default: #group name
            #build: true
    
# These groups correspond to the Permissions groups defined in your '<worldname>.yml'
Groups:
    Default: #group name
       Residence:
           # Determins if this group can create residences or not.  This option can be overriden with the permissions node 'residence.create'
           CanCreate: true
           # The maximum number of Residences a player can have.
           MaxResidences: 3
           # The maximum number of blocks a Residence can be, East to West (X).
           MaxEastWest: 16
           # The maximum number of blocks a Residence can be, North to South (Z).
           MaxNorthSouth: 16
           # The maximum number of blocks a Residence can be, High to Low (Y).
           MaxUpDown: 256
           # The lowest altitude this group is allowed to protect.
           MinHeight: 0
           # The highest altitude this group is allowed to protect.
           MaxHeight: 255
           # Whether or not to allow teleporting to Residences.
           CanTeleport: true
           # Allow or Disallow the use of /res unstuck, to get yourself out of a residence if stuck in one somehow
           Unstuck: true
           # Allow or Disallow the use of /res kick, to kick player from residence.
           Kick: false
           # Allow or Disallow the use of the /res select command, if disabled they can only use the selection tool.
           SelectCommandAccess: true
       # Options relating to enter and leave messages on the residence.
       Messaging:
           # Whether or not the player can change the Residence enter and leave messages.
           CanChange: true
           # The default enter message to apply to new Residences created by players in this group.
           # Leaving the message blank will disable it.
           DefaultEnter: Welcome %player to %residence, owned by %owner.
           # The default leave message to apply to new Residences created by players in this group.
           # Leaving the message blank will disable it.
           DefaultLeave: Now leaving %residence.
       # Options relating to the Residence Economy.
       Economy:
          # Whether or not players in this group can buy other Residences that are for sale.
          CanBuy: true
          # Whether or not players in this group can sell their Residences.
          CanSell: false
          # Whether or not to ignore the Residence size/count limits when buying a residence.
          IgnoreLimits: false
          # The cost, per block, of making a new Residence or adding a area to it.
          BuyCost: 0.05
       # Flags are checked in the order:
       # 1: Player
       # 2: Group
       # 3: Owner
       # 4: If all others are undefined, reverts to default value (usually true).
       # Flag permissions default to false.
       # These flags settings override the globals.
       Flags:
          # Specifically allow or deny this group from changing certain flags.
          Permission:
               #build: true
          # Specifys the flags that are applied at residence creation for players of this group.
          Default:
              #build: true
          # Specifys the flags that are applied at to the creator at residence creation.
          CreatorDefault:
              #build: true
          # Specifys the flags that are applied to other groups for this residence, at creation.
          GroupDefault:
               #default: #group name
                   #build: false
